import {createActions} from 'redux-actions';

/**
 * creates actions for redux
 * @method actionCreators
 */
export const actionCreators = createActions({
  notifications: {
    setNotifications: undefined,
    appendNotifications: undefined,
    addNewNotification: undefined,
    setUnseenNotificationsCount: undefined,
    increaseUnseenNotificationCount: undefined,
    decreaseUnseenNotificationCount: undefined,
    addNewFriendshipRequest: undefined,
    setBadgeNotificationCount: undefined,
    increaseBadgeNotificationCount: undefined,
    addNotifications: undefined,
    fetchNotifications: undefined,
    loadMoreNotifications: undefined,
    updateSingleNotification: undefined,
    initMarkAsSeen: undefined,
    markAsSeen: undefined,
    cancel: undefined,
    refreshNotifications: undefined,
    setFriendshipRequests: undefined,
    deleteFriendshipReject: undefined,
  },
  paperPlanes: {
    set: undefined,
    prepend: undefined,
    fetchMyProfilePPEntries: undefined,
    reset: undefined,
    setFocusIndex: undefined,
  },
  myProfile: {
    setFailedPPs: undefined,
    setPaperPlanes: undefined,
    deletePaperPlane: undefined,
    appendPaperPlanes: undefined,
  },
  chatRoom: {
    setRooms: undefined,
    setInActiveRooms: undefined,
    addNewRoom: undefined,
    deleteRoom: undefined,
    deleteInActiveRoom: undefined,
    setLoading: undefined,
    setLoadingSingleRoom: undefined,
    setRoomMessages: undefined,
    addNewMessage: undefined,
    addRoomMember: undefined,
    updateRoomMember: undefined,
    updateRoomMemberAppUser: undefined,
    updatePoll: undefined,
    updatePollStatus: undefined,
    reUploadMessage: undefined,
    updateMessagesEvents: undefined,
    updateRepliesList: undefined,
    updateMessagesLoadedStatus: undefined,
    updateSuccessfullySentMessage: undefined,
    loadingMessages: undefined,
    removingMember: undefined,
    resetNewMessageCount: undefined,
    deleteMessage: undefined,
    updateMessageReactions: undefined,
    extendRoom: undefined,
    addSubscription: undefined,
    removeSubscription: undefined,
  },
  directChat: {
    setDirectChatsList: undefined,
    addNewDirectChat: undefined,
    setLoading: undefined,
    setLoadingSingleChat: undefined,
    setDirectChatMessages: undefined,
    addNewDirectMessage: undefined,
    updateMessagesLoadedStatus: undefined,
    updateSuccessfullySentDirectMessage: undefined,
    loadingMessages: undefined,
    updateMessageReactions: undefined,
    addSubscription: undefined,
    removeSubscription: undefined,
    setAcceptBlock: undefined,
    enterChat: undefined,
    resetNewMessageCount: undefined,
    setCurrentActiveRoom: undefined,
  },
  popup: {
    setPopup: undefined,
  },
  inspirations: {
    setInspirations: undefined,
    addInspiration: undefined,
    deleteInspiration: undefined,
    reorderInspiration: undefined,
  },
  netInfo: {
    setNetInfo: undefined,
  },
  userProfile: {
    updateRoles: undefined,
    setLoading: undefined,
    setUserProfileDetails: undefined,
    updateProfileImage: undefined,
    updateFriendships: undefined,
    deleteFriendship: undefined,
    setPrompts: undefined,
  },
  appStatus: {
    setdynamicLink: undefined,
    setPushNotifAllowed: undefined,
    setAudioAllowed: undefined,
    setLocationAllowed: undefined,
    setAskedForNotificationPermissions: undefined,
    markTapToShare: undefined,
    markFirstRoom: undefined,
    markWelcomeRoomVisited: undefined,
    markOnboardingRoomsSeen: undefined,
    markOnboardingRoomsThisWeekSeen: undefined,
    markOnboardingSwipeUpSeen: undefined,
    markSignUpInProgress: undefined,
    setNewFeatureList: undefined,
    markNewFeatureListSeen: undefined,
    setAppState: undefined,
    resetAppState: undefined,
    setInstalledNewUpdate: undefined,
    setInviteFriendPopUpSeen: undefined,
    setShowInitialLoadingIndicator: undefined,
  },
  navigation: {
    setNavigationInformation: undefined,
    clearNavigationInformation: undefined,
  },
  replies: {
    setReplies: undefined,
    setUploadingNewReplyStatus: undefined,
    setNewReplyPreloaderStatus: undefined,
    setDeletingStatus: undefined,
  },
  bottomTabBar: {
    setVisibility: undefined,
  },
  referrals: {
    setReferrals: undefined,
    setInviteLink: undefined,
  },
});
