import React from 'react';
import { StyleSheet, Dimensions } from 'react-native';
import Globals from '../../component-library/Globals';
import { windowWidth } from '../ChatRoom/ChatroomUtils';

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    backgroundColor: Globals.color.background.light,
  },
  containerBackground: {
    width: '100%',
    height: '100%',
    backgroundColor: Globals.color.background.dark,
  },
  listItem: {
    flexDirection: 'row',
    paddingHorizontal: Globals.dimension.padding.small,
    paddingVertical: Globals.dimension.padding.tiny,
    backgroundColor: Globals.color.background.light,
  },
  indentedListItem: {
    paddingLeft: Globals.dimension.padding.xlarge,
    paddingRight: Globals.dimension.padding.small,
  },
  headerTime: {
    textAlign: 'center',
    fontSize: Globals.font.size.tiny,
    color: '#ABABAB',
    fontFamily: Globals.font.family.regular,
  },
  chatTitle: {
    fontSize: Globals.font.size.large,
    fontFamily: Globals.font.family.bold,
    color: Globals.color.text.default,
    paddingHorizontal: Globals.dimension.padding.medium,
    paddingVertical: Globals.dimension.padding.tiny,
    lineHeight: 25,
  },
  itemMainContainer: {
    flex: 1,
    backgroundColor: 'cadetblue',
  },
  avatarContainer: {
    backgroundColor: Globals.color.background.light,
    borderRadius: 100,
    width: 44,
    height: 44,
    elevation: 15,
  },
  messageMainContainer: {
    flex: 1,
    flexDirection: 'column',
  },
  messageMainWrapper: {
    flex: 1,
    backgroundColor: '#F0F0F1',
    paddingLeft: 15,
    paddingRight: 15,
    paddingTop: 10,
    paddingBottom: 10,
    borderRadius: Globals.dimension.borderRadius.mini,
  },
  messageFirstRowContainer: {
    flexDirection: 'row',
    paddingBottom: 1,
  },
  userName: {
    color: Globals.color.text.default,
    fontFamily: Globals.font.family.bold,
    fontSize: Globals.font.size.small,
    lineHeight: Globals.font.lineHeight.small,
  },
  messageCreatedAt: {
    textAlign: 'right',
    color: '#A3A3A3',
    fontFamily: Globals.font.family.regular,
    fontSize: Globals.font.size.tiny,
    lineHeight: Globals.font.lineHeight.tiny,
  },
  messageContent: {
    fontSize: Globals.font.size.small,
    color: Globals.color.text.default,
    fontFamily: Globals.font.family.regular,
    lineHeight: Globals.font.lineHeight.small,
  },
  footerContainer: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  tapAnyMessage: {
    fontFamily: Globals.font.family.semibold,
    fontSize: Globals.font.size.tiny,
    color: Globals.color.text.lightgrey,
  },
  dashedLine: {
    fontFamily: Globals.font.family.bold,
    fontSize: Globals.font.size.small,
    color: Globals.color.text.lightgrey,
    borderRadius: 100,
  },
  newMessages: {
    fontFamily: Globals.font.family.regular,
    fontSize: Globals.font.size.tiny,
    color: Globals.color.text.grey,
  },
  goDownContainer: {
    position: 'absolute',
    right: Dimensions.get('window').width / 20,
    top: Dimensions.get('window').height / 2,
    alignSelf: 'flex-end',
    width: 38,
    height: 38,
    backgroundColor: '#F1004E',
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  goDownWrapper: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textInputContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  textInput: {
    width: '92%',
    fontFamily: Globals.font.family.regular,
    fontSize: Globals.font.size.medium,
    color: Globals.color.text.default,
    lineHeight: Globals.font.lineHeight.medium * 0.85,
    top: -6,
    paddingRight: Globals.dimension.padding.tiny,
  },
  replyIcon: {
    width: 17,
    height: 13,
    marginRight: Globals.dimension.margin.tiny,
  },
  newReplyPopupContainer: {
    width: '100%',
    position: 'absolute',
    top: Dimensions.get('window').height / 10,
    justifyContent: 'center',
    backgroundColor: '#F4B302',
  },
  newReplyPopupWrapper: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F4B302',
    paddingHorizontal: Globals.dimension.padding.small,
  },
  newReplyPopupText: {
    fontFamily: Globals.font.family.bold,
    fontSize: Globals.font.size.small,
    color: Globals.color.brand.white,
    paddingVertical: Globals.dimension.padding.mini,
  },
  popupCloseIcon: {
    marginTop: 5,
    width: 30,
    height: 30,
  },
  newReplyPopupHitSlope: {
    top: 25,
    bottom: 25,
    left: windowWidth / 2,
    right: windowWidth / 2,
  },
  downArrow: {
    transform: [{ rotate: '180deg' }],
    width: 10,
    height: 15,
  },
  expiredContainer: {
    width: '100%',
    height: '100%',

    backgroundColor: Globals.color.background.light,
  },
  expiredWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  expiredTitle: {
    fontSize: Globals.font.size.large,
    fontFamily: Globals.font.family.bold,
    color: Globals.color.text.default,
    paddingHorizontal: Globals.dimension.padding.medium,
    paddingVertical: Globals.dimension.padding.tiny,
    lineHeight: 25,
    textAlign: 'center',
  },
  expiredDescription: {
    fontSize: Globals.font.size.large,
    fontFamily: Globals.font.family.regular,
    color: Globals.color.text.default,
    paddingHorizontal: Globals.dimension.padding.medium,
    lineHeight: 25,
    textAlign: 'center',
  },
  noMore: {
    width: Dimensions.get('window').width / 1.26,
    height: Dimensions.get('window').width / 1.5,
    marginTop: Globals.dimension.margin.medium,
  },
  roomClosedIcon: {
    width: 100,
    height: 100 * 0.91,
    marginVertical: Globals.dimension.margin.small,
  },
  failedMessageContainer: {
    width: 30,
    height: 30,
    borderRadius: 100,
    backgroundColor: Globals.color.brand.primary,
    borderWidth: 3,
    borderColor: Globals.color.background.light,
    elevation: 8,
    shadowOffset: {
      height: 10,
      width: 0,
    },
    shadowRadius: 16,
    shadowOpacity: 0.08,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'visible',
  },
  exclamationMark: {
    fontFamily: Globals.font.family.bold,
    fontSize: Globals.font.size.small,
    color: Globals.color.text.light,
  },
  buttonShadow: {
    backgroundColor: '#C4C4C4',
    borderRadius: Globals.dimension.borderRadius.large,
    elevation: 15,
  },
  confirmationQuestion: {
    fontFamily: Globals.font.family.regular,
    fontSize: Globals.font.size.small,
    textAlign: 'center',
    paddingBottom: Globals.dimension.padding.mini,
  },
  flatListContentContainerStyle: {
    paddingVertical: 10,
    justifyContent: 'center',
  },
  welcomeContainer: {
    width: '90%',
    alignSelf: 'center',
    backgroundColor: Globals.color.background.mediumgrey,
    borderRadius: Globals.dimension.borderRadius.tiny,
    paddingVertical: Globals.dimension.padding.tiny,
    paddingHorizontal: Globals.dimension.padding.mini,
    marginVertical: Globals.dimension.margin.mini,
  },
  welcome: {
    fontFamily: Globals.font.family.bold,
    fontSize: Globals.font.size.medium,
    color: Globals.color.text.default,
  },
  welcomeDescription: {
    fontFamily: Globals.font.family.regular,
    fontSize: Globals.font.size.small,
    color: Globals.color.text.grey,
    lineHeight: Globals.font.lineHeight.small,
  },
  linkHighlight: {
    fontFamily: Globals.font.family.bold,
    fontSize: Globals.font.size.small,
    color: Globals.color.text.default,
    lineHeight: Globals.font.lineHeight.small,
  },
  shadedThreat: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(255,255,255, 0.5)',
  },
  headerRightContainer: {
    flexDirection: 'row',
  },
  directAcceptBlockModalContainer: {
    backgroundColor: Globals.color.background.lightgrey,
    alignItems: 'center',
    borderWidth: 1,
    paddingTop: Globals.dimension.padding.tiny,
    borderColor: Globals.color.border.lightgrey,
  },
  directModalUsernameMain: {
    fontFamily: Globals.font.family.regular,
    lineHeight: Globals.font.lineHeight.tiny,
    fontSize: Globals.font.size.tiny,
  },
  directModalUsername: {
    fontFamily: Globals.font.family.bold,
    lineHeight: Globals.font.lineHeight.tiny,
    fontSize: Globals.font.size.tiny,
  },
  directModalAllowText: {
    textAlign: 'center',
    paddingBottom: Globals.dimension.padding.tiny,
    fontFamily: Globals.font.family.regular,
    lineHeight: Globals.font.lineHeight.tiny,
    borderColor: Globals.color.border.darkgrey,
    fontSize: Globals.font.size.xTiny,
    color: Globals.color.text.grey,
  },
  directModalAcceptButton: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '50%',
    height: 40,
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderColor: Globals.color.border.lightgrey,
  },
  directModalAcceptText: {
    fontSize: Globals.font.size.tiny,
    fontFamily: Globals.font.family.bold,
    color: Globals.color.button.blue,
  },
  directModalBlockButton: {
    width: '50%',
    alignItems: 'center',
    justifyContent: 'center',
    borderTopWidth: 1,
    borderColor: Globals.color.border.lightgrey,
  },
  directModalBlockText: {
    fontSize: Globals.font.size.tiny,
    fontFamily: Globals.font.family.bold,
    color: Globals.color.brand.primary,
  },
  senderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  additionalLeftIconAvatarContainer: {
    marginRight: Globals.dimension.margin.tiny,
  },
  additionalLeftIconUserName: {
    fontFamily: Globals.font.family.bold,
    fontSize: Globals.font.size.medium,
    color: Globals.color.text.default,
    flex: 1,
  },
});
